/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { BatchService } from "../batch.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BatchCreateInput } from "./BatchCreateInput";
import { Batch } from "./Batch";
import { BatchFindManyArgs } from "./BatchFindManyArgs";
import { BatchWhereUniqueInput } from "./BatchWhereUniqueInput";
import { BatchUpdateInput } from "./BatchUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BatchControllerBase {
  constructor(
    protected readonly service: BatchService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Batch })
  @nestAccessControl.UseRoles({
    resource: "Batch",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createBatch(@common.Body() data: BatchCreateInput): Promise<Batch> {
    return await this.service.createBatch({
      data: {
        ...data,

        asset: {
          connect: data.asset,
        },

        item: {
          connect: data.item,
        },

        productionOrder: {
          connect: data.productionOrder,
        },

        route: {
          connect: data.route,
        },
      },
      select: {
        asset: {
          select: {
            id: true,
          },
        },

        batchActualQty: true,
        batchClass: true,
        batchClassId: true,
        batchClassName: true,
        batchId: true,
        batchPlannedQty: true,
        batchUnits: true,
        id: true,

        item: {
          select: {
            id: true,
          },
        },

        productionOrder: {
          select: {
            id: true,
          },
        },

        route: {
          select: {
            id: true,
          },
        },

        status: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Batch] })
  @ApiNestedQuery(BatchFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Batch",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async batches(@common.Req() request: Request): Promise<Batch[]> {
    const args = plainToClass(BatchFindManyArgs, request.query);
    return this.service.batches({
      ...args,
      select: {
        asset: {
          select: {
            id: true,
          },
        },

        batchActualQty: true,
        batchClass: true,
        batchClassId: true,
        batchClassName: true,
        batchId: true,
        batchPlannedQty: true,
        batchUnits: true,
        id: true,

        item: {
          select: {
            id: true,
          },
        },

        productionOrder: {
          select: {
            id: true,
          },
        },

        route: {
          select: {
            id: true,
          },
        },

        status: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Batch })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Batch",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async batch(
    @common.Param() params: BatchWhereUniqueInput
  ): Promise<Batch | null> {
    const result = await this.service.batch({
      where: params,
      select: {
        asset: {
          select: {
            id: true,
          },
        },

        batchActualQty: true,
        batchClass: true,
        batchClassId: true,
        batchClassName: true,
        batchId: true,
        batchPlannedQty: true,
        batchUnits: true,
        id: true,

        item: {
          select: {
            id: true,
          },
        },

        productionOrder: {
          select: {
            id: true,
          },
        },

        route: {
          select: {
            id: true,
          },
        },

        status: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Batch })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Batch",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateBatch(
    @common.Param() params: BatchWhereUniqueInput,
    @common.Body() data: BatchUpdateInput
  ): Promise<Batch | null> {
    try {
      return await this.service.updateBatch({
        where: params,
        data: {
          ...data,

          asset: {
            connect: data.asset,
          },

          item: {
            connect: data.item,
          },

          productionOrder: {
            connect: data.productionOrder,
          },

          route: {
            connect: data.route,
          },
        },
        select: {
          asset: {
            select: {
              id: true,
            },
          },

          batchActualQty: true,
          batchClass: true,
          batchClassId: true,
          batchClassName: true,
          batchId: true,
          batchPlannedQty: true,
          batchUnits: true,
          id: true,

          item: {
            select: {
              id: true,
            },
          },

          productionOrder: {
            select: {
              id: true,
            },
          },

          route: {
            select: {
              id: true,
            },
          },

          status: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Batch })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Batch",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteBatch(
    @common.Param() params: BatchWhereUniqueInput
  ): Promise<Batch | null> {
    try {
      return await this.service.deleteBatch({
        where: params,
        select: {
          asset: {
            select: {
              id: true,
            },
          },

          batchActualQty: true,
          batchClass: true,
          batchClassId: true,
          batchClassName: true,
          batchId: true,
          batchPlannedQty: true,
          batchUnits: true,
          id: true,

          item: {
            select: {
              id: true,
            },
          },

          productionOrder: {
            select: {
              id: true,
            },
          },

          route: {
            select: {
              id: true,
            },
          },

          status: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
