/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Item, // @ts-ignore
  Batch, // @ts-ignore
  ProductionOrder,
} from "@prisma/client";

export class ItemServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.ItemCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.ItemCountArgs>
  ): Promise<number> {
    return this.prisma.item.count(args);
  }

  async items<T extends Prisma.ItemFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ItemFindManyArgs>
  ): Promise<Item[]> {
    return this.prisma.item.findMany(args);
  }
  async item<T extends Prisma.ItemFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ItemFindUniqueArgs>
  ): Promise<Item | null> {
    return this.prisma.item.findUnique(args);
  }
  async createItem<T extends Prisma.ItemCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ItemCreateArgs>
  ): Promise<Item> {
    return this.prisma.item.create<T>(args);
  }
  async updateItem<T extends Prisma.ItemUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ItemUpdateArgs>
  ): Promise<Item> {
    return this.prisma.item.update<T>(args);
  }
  async deleteItem<T extends Prisma.ItemDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.ItemDeleteArgs>
  ): Promise<Item> {
    return this.prisma.item.delete(args);
  }

  async findBatches(
    parentId: string,
    args: Prisma.BatchFindManyArgs
  ): Promise<Batch[]> {
    return this.prisma.item
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .batches(args);
  }

  async findProductionOrders(
    parentId: string,
    args: Prisma.ProductionOrderFindManyArgs
  ): Promise<ProductionOrder[]> {
    return this.prisma.item
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .productionOrders(args);
  }
}
