/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsBoolean,
  IsString,
  ValidateNested,
  IsOptional,
  IsDate,
} from "class-validator";
import { BatchCreateNestedManyWithoutItemsInput } from "./BatchCreateNestedManyWithoutItemsInput";
import { Type } from "class-transformer";
import { ProductionOrderCreateNestedManyWithoutItemsInput } from "./ProductionOrderCreateNestedManyWithoutItemsInput";

@InputType()
class ItemCreateInput {
  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  batchClassActive!: boolean;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  batchClassDescription!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  batchClassId!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  batchClassName!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  batchClassRevision!: string;

  @ApiProperty({
    required: false,
    type: () => BatchCreateNestedManyWithoutItemsInput,
  })
  @ValidateNested()
  @Type(() => BatchCreateNestedManyWithoutItemsInput)
  @IsOptional()
  @Field(() => BatchCreateNestedManyWithoutItemsInput, {
    nullable: true,
  })
  batches?: BatchCreateNestedManyWithoutItemsInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  className!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  createdBy!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  editedAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  editedBy!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  productionOrderId?: string | null;

  @ApiProperty({
    required: false,
    type: () => ProductionOrderCreateNestedManyWithoutItemsInput,
  })
  @ValidateNested()
  @Type(() => ProductionOrderCreateNestedManyWithoutItemsInput)
  @IsOptional()
  @Field(() => ProductionOrderCreateNestedManyWithoutItemsInput, {
    nullable: true,
  })
  productionOrders?: ProductionOrderCreateNestedManyWithoutItemsInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  schemaVersion!: string;
}

export { ItemCreateInput as ItemCreateInput };
