/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BatchUpdateManyWithoutProductionOrdersInput } from "./BatchUpdateManyWithoutProductionOrdersInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  IsDate,
  IsBoolean,
} from "class-validator";
import { Type } from "class-transformer";
import { RouteWhereUniqueInput } from "../../route/base/RouteWhereUniqueInput";
import { RouteRecipeUpdateManyWithoutProductionOrdersInput } from "./RouteRecipeUpdateManyWithoutProductionOrdersInput";
import { ItemWhereUniqueInput } from "../../item/base/ItemWhereUniqueInput";

@InputType()
class ProductionOrderUpdateInput {
  @ApiProperty({
    required: false,
    type: () => BatchUpdateManyWithoutProductionOrdersInput,
  })
  @ValidateNested()
  @Type(() => BatchUpdateManyWithoutProductionOrdersInput)
  @IsOptional()
  @Field(() => BatchUpdateManyWithoutProductionOrdersInput, {
    nullable: true,
  })
  batches?: BatchUpdateManyWithoutProductionOrdersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  className?: string;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  createdAt?: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  createdBy?: string;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  editedAt?: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  editedBy?: string;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  endDate?: Date;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  firmed?: boolean;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  released?: boolean;

  @ApiProperty({
    required: false,
    type: () => RouteWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => RouteWhereUniqueInput)
  @IsOptional()
  @Field(() => RouteWhereUniqueInput, {
    nullable: true,
  })
  route?: RouteWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => RouteRecipeUpdateManyWithoutProductionOrdersInput,
  })
  @ValidateNested()
  @Type(() => RouteRecipeUpdateManyWithoutProductionOrdersInput)
  @IsOptional()
  @Field(() => RouteRecipeUpdateManyWithoutProductionOrdersInput, {
    nullable: true,
  })
  routeRecipes?: RouteRecipeUpdateManyWithoutProductionOrdersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  schemaVersion?: string;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  startDate?: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  state?: string;

  @ApiProperty({
    required: false,
    type: () => ItemWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ItemWhereUniqueInput)
  @IsOptional()
  @Field(() => ItemWhereUniqueInput, {
    nullable: true,
  })
  wipItem?: ItemWhereUniqueInput;
}

export { ProductionOrderUpdateInput as ProductionOrderUpdateInput };
