/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ProductionOrderService } from "../productionOrder.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProductionOrderCreateInput } from "./ProductionOrderCreateInput";
import { ProductionOrder } from "./ProductionOrder";
import { ProductionOrderFindManyArgs } from "./ProductionOrderFindManyArgs";
import { ProductionOrderWhereUniqueInput } from "./ProductionOrderWhereUniqueInput";
import { ProductionOrderUpdateInput } from "./ProductionOrderUpdateInput";
import { BatchFindManyArgs } from "../../batch/base/BatchFindManyArgs";
import { Batch } from "../../batch/base/Batch";
import { BatchWhereUniqueInput } from "../../batch/base/BatchWhereUniqueInput";
import { RouteRecipeFindManyArgs } from "../../routeRecipe/base/RouteRecipeFindManyArgs";
import { RouteRecipe } from "../../routeRecipe/base/RouteRecipe";
import { RouteRecipeWhereUniqueInput } from "../../routeRecipe/base/RouteRecipeWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ProductionOrderControllerBase {
  constructor(
    protected readonly service: ProductionOrderService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ProductionOrder })
  @nestAccessControl.UseRoles({
    resource: "ProductionOrder",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createProductionOrder(
    @common.Body() data: ProductionOrderCreateInput
  ): Promise<ProductionOrder> {
    return await this.service.createProductionOrder({
      data: {
        ...data,

        route: {
          connect: data.route,
        },

        wipItem: {
          connect: data.wipItem,
        },
      },
      select: {
        className: true,
        createdAt: true,
        createdBy: true,
        editedAt: true,
        editedBy: true,
        endDate: true,
        firmed: true,
        id: true,
        released: true,

        route: {
          select: {
            id: true,
          },
        },

        schemaVersion: true,
        startDate: true,
        state: true,

        wipItem: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ProductionOrder] })
  @ApiNestedQuery(ProductionOrderFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ProductionOrder",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async productionOrders(
    @common.Req() request: Request
  ): Promise<ProductionOrder[]> {
    const args = plainToClass(ProductionOrderFindManyArgs, request.query);
    return this.service.productionOrders({
      ...args,
      select: {
        className: true,
        createdAt: true,
        createdBy: true,
        editedAt: true,
        editedBy: true,
        endDate: true,
        firmed: true,
        id: true,
        released: true,

        route: {
          select: {
            id: true,
          },
        },

        schemaVersion: true,
        startDate: true,
        state: true,

        wipItem: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ProductionOrder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProductionOrder",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async productionOrder(
    @common.Param() params: ProductionOrderWhereUniqueInput
  ): Promise<ProductionOrder | null> {
    const result = await this.service.productionOrder({
      where: params,
      select: {
        className: true,
        createdAt: true,
        createdBy: true,
        editedAt: true,
        editedBy: true,
        endDate: true,
        firmed: true,
        id: true,
        released: true,

        route: {
          select: {
            id: true,
          },
        },

        schemaVersion: true,
        startDate: true,
        state: true,

        wipItem: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ProductionOrder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProductionOrder",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateProductionOrder(
    @common.Param() params: ProductionOrderWhereUniqueInput,
    @common.Body() data: ProductionOrderUpdateInput
  ): Promise<ProductionOrder | null> {
    try {
      return await this.service.updateProductionOrder({
        where: params,
        data: {
          ...data,

          route: {
            connect: data.route,
          },

          wipItem: {
            connect: data.wipItem,
          },
        },
        select: {
          className: true,
          createdAt: true,
          createdBy: true,
          editedAt: true,
          editedBy: true,
          endDate: true,
          firmed: true,
          id: true,
          released: true,

          route: {
            select: {
              id: true,
            },
          },

          schemaVersion: true,
          startDate: true,
          state: true,

          wipItem: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ProductionOrder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProductionOrder",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteProductionOrder(
    @common.Param() params: ProductionOrderWhereUniqueInput
  ): Promise<ProductionOrder | null> {
    try {
      return await this.service.deleteProductionOrder({
        where: params,
        select: {
          className: true,
          createdAt: true,
          createdBy: true,
          editedAt: true,
          editedBy: true,
          endDate: true,
          firmed: true,
          id: true,
          released: true,

          route: {
            select: {
              id: true,
            },
          },

          schemaVersion: true,
          startDate: true,
          state: true,

          wipItem: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/batches")
  @ApiNestedQuery(BatchFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Batch",
    action: "read",
    possession: "any",
  })
  async findBatches(
    @common.Req() request: Request,
    @common.Param() params: ProductionOrderWhereUniqueInput
  ): Promise<Batch[]> {
    const query = plainToClass(BatchFindManyArgs, request.query);
    const results = await this.service.findBatches(params.id, {
      ...query,
      select: {
        asset: {
          select: {
            id: true,
          },
        },

        batchActualQty: true,
        batchClass: true,
        batchClassId: true,
        batchClassName: true,
        batchId: true,
        batchPlannedQty: true,
        batchUnits: true,
        id: true,

        item: {
          select: {
            id: true,
          },
        },

        productionOrder: {
          select: {
            id: true,
          },
        },

        route: {
          select: {
            id: true,
          },
        },

        status: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/batches")
  @nestAccessControl.UseRoles({
    resource: "ProductionOrder",
    action: "update",
    possession: "any",
  })
  async connectBatches(
    @common.Param() params: ProductionOrderWhereUniqueInput,
    @common.Body() body: BatchWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      batches: {
        connect: body,
      },
    };
    await this.service.updateProductionOrder({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/batches")
  @nestAccessControl.UseRoles({
    resource: "ProductionOrder",
    action: "update",
    possession: "any",
  })
  async updateBatches(
    @common.Param() params: ProductionOrderWhereUniqueInput,
    @common.Body() body: BatchWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      batches: {
        set: body,
      },
    };
    await this.service.updateProductionOrder({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/batches")
  @nestAccessControl.UseRoles({
    resource: "ProductionOrder",
    action: "update",
    possession: "any",
  })
  async disconnectBatches(
    @common.Param() params: ProductionOrderWhereUniqueInput,
    @common.Body() body: BatchWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      batches: {
        disconnect: body,
      },
    };
    await this.service.updateProductionOrder({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/routeRecipes")
  @ApiNestedQuery(RouteRecipeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "RouteRecipe",
    action: "read",
    possession: "any",
  })
  async findRouteRecipes(
    @common.Req() request: Request,
    @common.Param() params: ProductionOrderWhereUniqueInput
  ): Promise<RouteRecipe[]> {
    const query = plainToClass(RouteRecipeFindManyArgs, request.query);
    const results = await this.service.findRouteRecipes(params.id, {
      ...query,
      select: {
        id: true,
        operationStepId: true,
        operationStepName: true,

        productionOrder: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/routeRecipes")
  @nestAccessControl.UseRoles({
    resource: "ProductionOrder",
    action: "update",
    possession: "any",
  })
  async connectRouteRecipes(
    @common.Param() params: ProductionOrderWhereUniqueInput,
    @common.Body() body: RouteRecipeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      routeRecipes: {
        connect: body,
      },
    };
    await this.service.updateProductionOrder({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/routeRecipes")
  @nestAccessControl.UseRoles({
    resource: "ProductionOrder",
    action: "update",
    possession: "any",
  })
  async updateRouteRecipes(
    @common.Param() params: ProductionOrderWhereUniqueInput,
    @common.Body() body: RouteRecipeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      routeRecipes: {
        set: body,
      },
    };
    await this.service.updateProductionOrder({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/routeRecipes")
  @nestAccessControl.UseRoles({
    resource: "ProductionOrder",
    action: "update",
    possession: "any",
  })
  async disconnectRouteRecipes(
    @common.Param() params: ProductionOrderWhereUniqueInput,
    @common.Body() body: RouteRecipeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      routeRecipes: {
        disconnect: body,
      },
    };
    await this.service.updateProductionOrder({
      where: params,
      data,
      select: { id: true },
    });
  }
}
