/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { ProductionOrder } from "./ProductionOrder";
import { ProductionOrderCountArgs } from "./ProductionOrderCountArgs";
import { ProductionOrderFindManyArgs } from "./ProductionOrderFindManyArgs";
import { ProductionOrderFindUniqueArgs } from "./ProductionOrderFindUniqueArgs";
import { CreateProductionOrderArgs } from "./CreateProductionOrderArgs";
import { UpdateProductionOrderArgs } from "./UpdateProductionOrderArgs";
import { DeleteProductionOrderArgs } from "./DeleteProductionOrderArgs";
import { BatchFindManyArgs } from "../../batch/base/BatchFindManyArgs";
import { Batch } from "../../batch/base/Batch";
import { RouteRecipeFindManyArgs } from "../../routeRecipe/base/RouteRecipeFindManyArgs";
import { RouteRecipe } from "../../routeRecipe/base/RouteRecipe";
import { Route } from "../../route/base/Route";
import { Item } from "../../item/base/Item";
import { ProductionOrderService } from "../productionOrder.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ProductionOrder)
export class ProductionOrderResolverBase {
  constructor(
    protected readonly service: ProductionOrderService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ProductionOrder",
    action: "read",
    possession: "any",
  })
  async _productionOrdersMeta(
    @graphql.Args() args: ProductionOrderCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ProductionOrder])
  @nestAccessControl.UseRoles({
    resource: "ProductionOrder",
    action: "read",
    possession: "any",
  })
  async productionOrders(
    @graphql.Args() args: ProductionOrderFindManyArgs
  ): Promise<ProductionOrder[]> {
    return this.service.productionOrders(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ProductionOrder, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ProductionOrder",
    action: "read",
    possession: "own",
  })
  async productionOrder(
    @graphql.Args() args: ProductionOrderFindUniqueArgs
  ): Promise<ProductionOrder | null> {
    const result = await this.service.productionOrder(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ProductionOrder)
  @nestAccessControl.UseRoles({
    resource: "ProductionOrder",
    action: "create",
    possession: "any",
  })
  async createProductionOrder(
    @graphql.Args() args: CreateProductionOrderArgs
  ): Promise<ProductionOrder> {
    return await this.service.createProductionOrder({
      ...args,
      data: {
        ...args.data,

        route: {
          connect: args.data.route,
        },

        wipItem: {
          connect: args.data.wipItem,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ProductionOrder)
  @nestAccessControl.UseRoles({
    resource: "ProductionOrder",
    action: "update",
    possession: "any",
  })
  async updateProductionOrder(
    @graphql.Args() args: UpdateProductionOrderArgs
  ): Promise<ProductionOrder | null> {
    try {
      return await this.service.updateProductionOrder({
        ...args,
        data: {
          ...args.data,

          route: {
            connect: args.data.route,
          },

          wipItem: {
            connect: args.data.wipItem,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ProductionOrder)
  @nestAccessControl.UseRoles({
    resource: "ProductionOrder",
    action: "delete",
    possession: "any",
  })
  async deleteProductionOrder(
    @graphql.Args() args: DeleteProductionOrderArgs
  ): Promise<ProductionOrder | null> {
    try {
      return await this.service.deleteProductionOrder(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Batch], { name: "batches" })
  @nestAccessControl.UseRoles({
    resource: "Batch",
    action: "read",
    possession: "any",
  })
  async findBatches(
    @graphql.Parent() parent: ProductionOrder,
    @graphql.Args() args: BatchFindManyArgs
  ): Promise<Batch[]> {
    const results = await this.service.findBatches(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [RouteRecipe], { name: "routeRecipes" })
  @nestAccessControl.UseRoles({
    resource: "RouteRecipe",
    action: "read",
    possession: "any",
  })
  async findRouteRecipes(
    @graphql.Parent() parent: ProductionOrder,
    @graphql.Args() args: RouteRecipeFindManyArgs
  ): Promise<RouteRecipe[]> {
    const results = await this.service.findRouteRecipes(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Route, {
    nullable: true,
    name: "route",
  })
  @nestAccessControl.UseRoles({
    resource: "Route",
    action: "read",
    possession: "any",
  })
  async getRoute(
    @graphql.Parent() parent: ProductionOrder
  ): Promise<Route | null> {
    const result = await this.service.getRoute(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Item, {
    nullable: true,
    name: "wipItem",
  })
  @nestAccessControl.UseRoles({
    resource: "Item",
    action: "read",
    possession: "any",
  })
  async getWipItem(
    @graphql.Parent() parent: ProductionOrder
  ): Promise<Item | null> {
    const result = await this.service.getWipItem(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
