/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RouteService } from "../route.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RouteCreateInput } from "./RouteCreateInput";
import { Route } from "./Route";
import { RouteFindManyArgs } from "./RouteFindManyArgs";
import { RouteWhereUniqueInput } from "./RouteWhereUniqueInput";
import { RouteUpdateInput } from "./RouteUpdateInput";
import { BatchFindManyArgs } from "../../batch/base/BatchFindManyArgs";
import { Batch } from "../../batch/base/Batch";
import { BatchWhereUniqueInput } from "../../batch/base/BatchWhereUniqueInput";
import { ProductionOrderFindManyArgs } from "../../productionOrder/base/ProductionOrderFindManyArgs";
import { ProductionOrder } from "../../productionOrder/base/ProductionOrder";
import { ProductionOrderWhereUniqueInput } from "../../productionOrder/base/ProductionOrderWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RouteControllerBase {
  constructor(
    protected readonly service: RouteService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Route })
  @nestAccessControl.UseRoles({
    resource: "Route",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createRoute(@common.Body() data: RouteCreateInput): Promise<Route> {
    return await this.service.createRoute({
      data: data,
      select: {
        id: true,
        routeName: true,
        routeOperation: true,
        routeOperationStep: true,
        routeRevision: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Route] })
  @ApiNestedQuery(RouteFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Route",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async routes(@common.Req() request: Request): Promise<Route[]> {
    const args = plainToClass(RouteFindManyArgs, request.query);
    return this.service.routes({
      ...args,
      select: {
        id: true,
        routeName: true,
        routeOperation: true,
        routeOperationStep: true,
        routeRevision: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Route })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Route",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async route(
    @common.Param() params: RouteWhereUniqueInput
  ): Promise<Route | null> {
    const result = await this.service.route({
      where: params,
      select: {
        id: true,
        routeName: true,
        routeOperation: true,
        routeOperationStep: true,
        routeRevision: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Route })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Route",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateRoute(
    @common.Param() params: RouteWhereUniqueInput,
    @common.Body() data: RouteUpdateInput
  ): Promise<Route | null> {
    try {
      return await this.service.updateRoute({
        where: params,
        data: data,
        select: {
          id: true,
          routeName: true,
          routeOperation: true,
          routeOperationStep: true,
          routeRevision: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Route })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Route",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteRoute(
    @common.Param() params: RouteWhereUniqueInput
  ): Promise<Route | null> {
    try {
      return await this.service.deleteRoute({
        where: params,
        select: {
          id: true,
          routeName: true,
          routeOperation: true,
          routeOperationStep: true,
          routeRevision: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/batches")
  @ApiNestedQuery(BatchFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Batch",
    action: "read",
    possession: "any",
  })
  async findBatches(
    @common.Req() request: Request,
    @common.Param() params: RouteWhereUniqueInput
  ): Promise<Batch[]> {
    const query = plainToClass(BatchFindManyArgs, request.query);
    const results = await this.service.findBatches(params.id, {
      ...query,
      select: {
        asset: {
          select: {
            id: true,
          },
        },

        batchActualQty: true,
        batchClass: true,
        batchClassId: true,
        batchClassName: true,
        batchId: true,
        batchPlannedQty: true,
        batchUnits: true,
        id: true,

        item: {
          select: {
            id: true,
          },
        },

        productionOrder: {
          select: {
            id: true,
          },
        },

        route: {
          select: {
            id: true,
          },
        },

        status: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/batches")
  @nestAccessControl.UseRoles({
    resource: "Route",
    action: "update",
    possession: "any",
  })
  async connectBatches(
    @common.Param() params: RouteWhereUniqueInput,
    @common.Body() body: BatchWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      batches: {
        connect: body,
      },
    };
    await this.service.updateRoute({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/batches")
  @nestAccessControl.UseRoles({
    resource: "Route",
    action: "update",
    possession: "any",
  })
  async updateBatches(
    @common.Param() params: RouteWhereUniqueInput,
    @common.Body() body: BatchWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      batches: {
        set: body,
      },
    };
    await this.service.updateRoute({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/batches")
  @nestAccessControl.UseRoles({
    resource: "Route",
    action: "update",
    possession: "any",
  })
  async disconnectBatches(
    @common.Param() params: RouteWhereUniqueInput,
    @common.Body() body: BatchWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      batches: {
        disconnect: body,
      },
    };
    await this.service.updateRoute({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/productionOrder")
  @ApiNestedQuery(ProductionOrderFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ProductionOrder",
    action: "read",
    possession: "any",
  })
  async findProductionOrder(
    @common.Req() request: Request,
    @common.Param() params: RouteWhereUniqueInput
  ): Promise<ProductionOrder[]> {
    const query = plainToClass(ProductionOrderFindManyArgs, request.query);
    const results = await this.service.findProductionOrder(params.id, {
      ...query,
      select: {
        className: true,
        createdAt: true,
        createdBy: true,
        editedAt: true,
        editedBy: true,
        endDate: true,
        firmed: true,
        id: true,
        released: true,

        route: {
          select: {
            id: true,
          },
        },

        schemaVersion: true,
        startDate: true,
        state: true,

        wipItem: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/productionOrder")
  @nestAccessControl.UseRoles({
    resource: "Route",
    action: "update",
    possession: "any",
  })
  async connectProductionOrder(
    @common.Param() params: RouteWhereUniqueInput,
    @common.Body() body: ProductionOrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productionOrder: {
        connect: body,
      },
    };
    await this.service.updateRoute({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/productionOrder")
  @nestAccessControl.UseRoles({
    resource: "Route",
    action: "update",
    possession: "any",
  })
  async updateProductionOrder(
    @common.Param() params: RouteWhereUniqueInput,
    @common.Body() body: ProductionOrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productionOrder: {
        set: body,
      },
    };
    await this.service.updateRoute({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/productionOrder")
  @nestAccessControl.UseRoles({
    resource: "Route",
    action: "update",
    possession: "any",
  })
  async disconnectProductionOrder(
    @common.Param() params: RouteWhereUniqueInput,
    @common.Body() body: ProductionOrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productionOrder: {
        disconnect: body,
      },
    };
    await this.service.updateRoute({
      where: params,
      data,
      select: { id: true },
    });
  }
}
