/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested, IsEnum } from "class-validator";
import { BatchUpdateManyWithoutAssetsInput } from "./BatchUpdateManyWithoutAssetsInput";
import { Type } from "class-transformer";
import { AssetUpdateManyWithoutAssetsInput } from "./AssetUpdateManyWithoutAssetsInput";
import { AssetWhereUniqueInput } from "./AssetWhereUniqueInput";
import { EnumAssetType } from "./EnumAssetType";

@InputType()
class AssetUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  assetDescription?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  assetName?: string;

  @ApiProperty({
    required: false,
    type: () => BatchUpdateManyWithoutAssetsInput,
  })
  @ValidateNested()
  @Type(() => BatchUpdateManyWithoutAssetsInput)
  @IsOptional()
  @Field(() => BatchUpdateManyWithoutAssetsInput, {
    nullable: true,
  })
  batches?: BatchUpdateManyWithoutAssetsInput;

  @ApiProperty({
    required: false,
    type: () => AssetUpdateManyWithoutAssetsInput,
  })
  @ValidateNested()
  @Type(() => AssetUpdateManyWithoutAssetsInput)
  @IsOptional()
  @Field(() => AssetUpdateManyWithoutAssetsInput, {
    nullable: true,
  })
  children?: AssetUpdateManyWithoutAssetsInput;

  @ApiProperty({
    required: false,
    type: () => AssetWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AssetWhereUniqueInput)
  @IsOptional()
  @Field(() => AssetWhereUniqueInput, {
    nullable: true,
  })
  parent?: AssetWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    enum: EnumAssetType,
  })
  @IsEnum(EnumAssetType)
  @IsOptional()
  @Field(() => EnumAssetType, {
    nullable: true,
  })
  type?:
    | "ENT"
    | "SITE"
    | "AREA"
    | "LINE"
    | "CELL"
    | "EQUIPMOD"
    | "EQUIPPHASE"
    | "CONTROLMOD";
}

export { AssetUpdateInput as AssetUpdateInput };
