/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested, IsEnum } from "class-validator";
import { BatchListRelationFilter } from "../../batch/base/BatchListRelationFilter";
import { AssetListRelationFilter } from "./AssetListRelationFilter";
import { AssetWhereUniqueInput } from "./AssetWhereUniqueInput";
import { EnumAssetType } from "./EnumAssetType";

@InputType()
class AssetWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  assetDescription?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  assetName?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => BatchListRelationFilter,
  })
  @ValidateNested()
  @Type(() => BatchListRelationFilter)
  @IsOptional()
  @Field(() => BatchListRelationFilter, {
    nullable: true,
  })
  batches?: BatchListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => AssetListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AssetListRelationFilter)
  @IsOptional()
  @Field(() => AssetListRelationFilter, {
    nullable: true,
  })
  children?: AssetListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => AssetWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AssetWhereUniqueInput)
  @IsOptional()
  @Field(() => AssetWhereUniqueInput, {
    nullable: true,
  })
  parent?: AssetWhereUniqueInput;

  @ApiProperty({
    required: false,
    enum: EnumAssetType,
  })
  @IsEnum(EnumAssetType)
  @IsOptional()
  @Field(() => EnumAssetType, {
    nullable: true,
  })
  type?:
    | "ENT"
    | "SITE"
    | "AREA"
    | "LINE"
    | "CELL"
    | "EQUIPMOD"
    | "EQUIPPHASE"
    | "CONTROLMOD";
}

export { AssetWhereInput as AssetWhereInput };
